spring:
  redis:
    database: 0
    host: 59.110.22.142
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  rabbitmq:
    host: 59.110.22.142
    port: 5672
    username: guest
    password: guest
